version: '3.8'

services:
  neo4j:
    image: neo4j:4.4
    container_name: assignment-neo4j
    ports:
      - "7474:7474"    
      - "7687:7687"    
    volumes:
      - neo4j_data:/data
    environment:
      NEO4J_AUTH: "neo4j/changeme"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: assignment-backend
    ports:
      - "8080:8080"
    depends_on:
      - neo4j
    environment:
      NEO4J_URI:  bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASS: changeme
      PORT:       8080
      SEED_DATA:  "true"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: assignment-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  neo4j_data:
